apiVersion: batch/v1
kind: Job
metadata:
  name: kubetls
spec:
  template:
    spec:
      containers:
      - name: kubetls
        image: nyrahul/tlsscan:latest
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
